useDotenv: true
service: linebot-kateiheiwa
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  stage: dev
  layers:
    - { Ref: PythonRequirementsLambdaLayer }

functions:
  linebot-kateiheiwa:
    handler: handler.handler
    environment:
      LINE_ACCESS_TOKEN: ${env:LINE_ACCESS_TOKEN, ""}
      LINE_CHANNEL_SECRET: ${env:LINE_CHANNEL_SECRET, ""}
      MY_LINE_USER_ID: ${env:MY_LINE_USER_ID, ""}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true # __pycache__とかいらないものを消してくれる。
    zip: true  # scipyとか大きいモジュールをzip化してくれる。
    useDownloadCache: true # デプロイ時、pipライブラリをキャッシュして使う。
    useStaticCache: true
    layer:
      name: ${self:provider.stage}-requirementLayer
      description: Python requirements lambda layer
      compatibleRuntimes:
        - python3.8
